project_id = "ipholpmeblfnkbbereih"

[functions.seed-answer-keys]
verify_jwt = false

[functions.toss-payment]
verify_jwt = false

[functions.toss-refund]
verify_jwt = false

[functions.toss-webhook]
verify_jwt = false

[functions.generate-discount-code]
verify_jwt = false
